services:
  app-backend:
    build: .
    ports:
      - "9000:9000"
    env_file:
      - .env.back
      - .env.db
  postgresql:
    image: "postgres:16-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env.db
