auth0:
  audience: zakaoai6.ddns.net
  domain : zakaoai.eu.auth0.com
  management:
    domain: zakaoai.eu.auth0.com
    clientId: WuB83Crd8srij5IyNMJtDCm7VPtQj5Yc
    clientSecret: ${AUTH0_MANAGEMENT_CLIENT_SECRET}
    audience: https://zakaoai.eu.auth0.com/api/v2/

spring:
  security:
    oauth2:
      resourceserver:
        id: zakaoai6.ddns.net
        jwt:
          jwk-set-uri: https://zakaoai.eu.auth0.com/.well-known/jwks.json
          issuer-uri: https://zakaoai.eu.auth0.com/
  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    enabled: 'true'
  application:
    name: cold-library-backend
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    user: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
security:
  basic:
    enabled: 'false'
server:
  port: '9000'
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        security: TRACE

myanimelist:
  client-id: ${MYANIMELIST_CLIENT_ID}

deluge:
  host: ${DELUGE_HOST}
  password: ${DELUGE_PASSWORD}