auth0:
  audience: zakaoai6.ddns.net
  domain : zakaoai.eu.auth0.com

spring:
  security:
    oauth2:
      resourceserver:
        id: zakaoai6.ddns.net
        jwt:
          jwk-set-uri: https://zakaoai.eu.auth0.com/.well-known/jwks.json
          issuer-uri: https://zakaoai.eu.auth0.com/
  liquibase:
    url: jdbc:h2:file:./data/database
    password: ''
    enabled: 'true'
    user: sa
  application:
    name: cold-library-backend
  h2:
    console:
      path: /h2-ui
      enabled: 'true'
  r2dbc:
    password: ''
    url: r2dbc:h2:file://././data/database?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
security:
  basic:
    enabled: 'false'
server:
  port: '9000'
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        security: TRACE

