auth0:
  audience: zakaoai6.ddns.net
  domain : zakaoai.eu.auth0.com

spring:
  security:
    oauth2:
      resourceserver:
        id: zakaoai6.ddns.net
        jwt:
          jwk-set-uri: https://zakaoai.eu.auth0.com/.well-known/jwks.json
          issuer-uri: https://zakaoai.eu.auth0.com/
  liquibase:
    url: jdbc:postgresql://localhost:5432/projects?currentSchema=cold_library
    user: 'postgres'
    password: 'mysecretpassword'
    enabled: 'true'
  application:
    name: cold-library-backend
  h2:
    console:
      path: /h2-ui
      enabled: 'true'
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/projects?currentSchema=cold_library
    username: 'postgres'
    password: 'mysecretpassword'
security:
  basic:
    enabled: 'false'
server:
  port: '9000'
logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
        security: TRACE

