ALTER TABLE ANIMEEPISODES ALTER COLUMN ID RESTART WITH 3600
ALTER TABLE animes ALTER COLUMN ID RESTART WITH 1200
ALTER TABLE trackedanimetorrent ALTER COLUMN ID RESTART WITH 1100
ALTER TABLE animeepisodetorrent ALTER COLUMN ID RESTART WITH 2400