name: Build

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 17 ]
    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5
        with:
          add-job-summary-as-pr-comment: 'on-failure'
          build-scan-publish: true
          build-scan-terms-of-use-url: 'https://gradle.com/terms-of-service'
          build-scan-terms-of-use-agree: 'yes'
      - name: Build with Gradle
        run: ./gradlew build --scan
      - name: Tests
        run: gradle test
